services:
  koito-scrobbler:
    build: .
    container_name: koito-scrobbler
    restart: unless-stopped
    volumes:
      - ./spotify_cache:/app/.cache
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pgrep", "-f", "koito-scrobbler-service.py"]
      interval: 30s
      timeout: 10s
      retries: 3