services:
  koito-scrobbler:
    build: .
    container_name: koito-scrobbler
    restart: unless-stopped
    volumes:
      - ./.cache:/app/.cache
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      start_period: 60s
      retries: 5